### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by jochen777** [ewolff/SCS-ESI#1]
Hello Eberhard,
I just wanted to try out this, everything went fine until "docker-compose build":

> docker-compose build
> Building catalog
> Step 1 : FROM ewolff/docker-java
> latest: Pulling from ewolff/docker-java
> c862d82a67a2: Pull complete
> a3ed95caeb02: Pull complete
> eb7afce74b5b: Pull complete
> Digest: sha256:bcb1e79929d2334edef90fbb4a80b07aafe74fcbb8b0a28d5e085d366c9ff6d5
> Status: Downloaded newer image for ewolff/docker-java:latest
>  ---> 051556b239ed
> Step 2 : ADD target/microservice-demo-catalog-0.0.1-SNAPSHOT.jar .
> **ERROR: Service 'catalog' failed to build: lstat target/microservice-demo-catalog-0.0.1-SNAPSHOT.jar: no such file or directory**

Is this target maybe missing?

 best regards -- Jochen

**Comment by ewolff** [comment]
Hi,
Please do a git pull. This should be fixed now.
Best regards,
Eberhard

**Comment by ewolff** [comment]
Hi,
I forgot to push. Please try again and close the issue if it is fixed.
Thanks!
Eberhard

**Comment by jochen777** [comment]
Now it works - thank you!
